import 'dart:io';
import 'dart:math';
import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/foundation.dart';

class SoundService {
  SoundService._();

  static final _player = AudioPlayer();
  static const _sr = 44100;

  static const _definitions = <String, List<(double, double)>>{
    'tick':      [(880.0, 0.12)],
    'focus_end': [(659.0, 0.55), (523.0, 0.50)],
    'break_end': [(523.0, 0.22), (784.0, 0.45)],
    'complete':  [(523.0, 0.22), (659.0, 0.22), (784.0, 0.55)],
  };

  // Web: keep generated bytes in memory (no filesystem available).
  static final _webCache = <String, Uint8List>{};

  static Future<void> init() async {
    if (kIsWeb) {
      for (final e in _definitions.entries) {
        _webCache[e.key] = _buildWav(e.value);
      }
      return;
    }
    await Future.wait(
      _definitions.entries.map((e) => _write(e.key, e.value)),
    );
  }

  static String _path(String name) =>
      '${Directory.systemTemp.path}/flowdo_$name.wav';

  static Future<void> _write(String name, List<(double, double)> notes) =>
      File(_path(name)).writeAsBytes(_buildWav(notes), flush: true);

  static Future<void> _play(String name) async {
    try {
      await _player.stop();
      if (kIsWeb) {
        final bytes = _webCache[name];
        if (bytes != null) await _player.play(BytesSource(bytes));
      } else {
        await _player.play(DeviceFileSource(_path(name)));
      }
    } catch (_) {}
  }

  static Uint8List _buildWav(List<(double freq, double dur)> notes) {
    final gapSamples = (_sr * 0.015).toInt(); // 15 ms silence between notes
    final pcm = <int>[];

    for (var ni = 0; ni < notes.length; ni++) {
      final (freq, dur) = notes[ni];
      final n = (_sr * dur).round();
      const attackSecs = 0.025; // 25 ms soft attack
      final releaseSecs = (dur * 0.30).clamp(0.04, 0.18);
      final releaseStart = dur - releaseSecs;

      for (var i = 0; i < n; i++) {
        final t = i / _sr;

        // Smooth ADSR: linear attack → gentle exponential decay → linear release
        final attack = (t / attackSecs).clamp(0.0, 1.0);
        final release = t >= releaseStart
            ? 1.0 - ((t - releaseStart) / releaseSecs).clamp(0.0, 1.0)
            : 1.0;
        final decay = exp(-1.8 * t / dur);
        final env = attack * release * decay * 0.33;

        // Pure tone with a single soft 2nd harmonic — no harsh overtones
        final wave = sin(2 * pi * freq * t) + 0.10 * sin(4 * pi * freq * t);

        final s = (wave * env * 32767).clamp(-32767.0, 32767.0).round();
        pcm.add(s & 0xFF);
        pcm.add((s >> 8) & 0xFF);
      }

      // Silence gap between notes (skip after last note)
      if (ni < notes.length - 1) {
        for (var i = 0; i < gapSamples; i++) {
          pcm.add(0);
          pcm.add(0);
        }
      }
    }

    return _wav(pcm);
  }

  static Uint8List _wav(List<int> pcm) {
    final h = ByteData(44);
    void str(int off, String s) {
      for (var i = 0; i < s.length; i++) {
        h.setUint8(off + i, s.codeUnitAt(i));
      }
    }
    str(0, 'RIFF');
    h.setUint32(4, 36 + pcm.length, Endian.little);
    str(8, 'WAVE');
    str(12, 'fmt ');
    h.setUint32(16, 16, Endian.little);
    h.setUint16(20, 1, Endian.little);
    h.setUint16(22, 1, Endian.little);
    h.setUint32(24, _sr, Endian.little);
    h.setUint32(28, _sr * 2, Endian.little);
    h.setUint16(32, 2, Endian.little);
    h.setUint16(34, 16, Endian.little);
    str(36, 'data');
    h.setUint32(40, pcm.length, Endian.little);
    return Uint8List.fromList([...h.buffer.asUint8List(), ...pcm]);
  }

  static Future<void> tick() => _play('tick');
  static Future<void> focusEnd() => _play('focus_end');
  static Future<void> breakEnd() => _play('break_end');
  static Future<void> sessionComplete() => _play('complete');
}
